[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "TisRyno"
name = "LethalCompanyProgressionPatchFix"
description = "An RPG-style XP-based levelling and skillpoint system, with a full custom GUI to manage your points."
websiteUrl = "https://github.com/TisRyno/LethalProgression"
containsNsfwContent = false

[package.dependencies]
# https://thunderstore.io/c/lethal-company/p/BepInEx/BepInExPack/
BepInEx-BepInExPack = "5.4.2100"
xilophor-LethalNetworkAPI = "2.1.6"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

[[build.copy]]
source = "LethalProgression/bin/LethalProgression.dll"
target = "LethalProgression.dll"

[[build.copy]]
source = "CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = ["lethal-company"]

[publish.categories]
# The categories are available at https://thunderstore.io near of the search bar
lethal-company = ["bepinex", "mods", "misc", "serverside", "clientside"]